services:
  watchtower:
    container_name: watchtower
    image: containrrr/watchtower:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=${TIMEZONE:-America/New_York}
      # Only update containers with the label
      - WATCHTOWER_LABEL_ENABLE=true
      # Schedule: Check daily at 3 AM (when you're likely asleep)
      - WATCHTOWER_SCHEDULE=0 0 3 * * *
      # Docker Hub authentication to avoid rate limits
      - REPO_USER=${DOCKER_HUB_USERNAME}
      - REPO_PASS=${DOCKER_HUB_PASSWORD}
      # Email notification settings (uses environment variables for security)
      - WATCHTOWER_NOTIFICATIONS=email
      - WATCHTOWER_NOTIFICATION_EMAIL_FROM=${WATCHTOWER_EMAIL}
      - WATCHTOWER_NOTIFICATION_EMAIL_TO=${WATCHTOWER_EMAIL}
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER=smtp.gmail.com
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT=587
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER=${WATCHTOWER_EMAIL}
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD=${WATCHTOWER_EMAIL_PASSWORD}
      # Safety settings
      - WATCHTOWER_MONITOR_ONLY=false  # Set to true for notifications only
      - WATCHTOWER_CLEANUP=true        # Remove old images after update
      - WATCHTOWER_INCLUDE_STOPPED=false
      - WATCHTOWER_REVIVE_STOPPED=false
      # Logging
      - WATCHTOWER_LOG_LEVEL=info
      # Rolling restart (update one at a time)
      - WATCHTOWER_ROLLING_RESTART=true
      # Additional settings to handle registry issues
      - WATCHTOWER_HTTP_API_UPDATE=true
      - WATCHTOWER_HTTP_API_PERIODIC_POLLS=true
    healthcheck:
      test: ["CMD", "/watchtower", "--help"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    labels:
      - "com.centurylinklabs.watchtower.enable=false"