networks:
  portainer_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/16
  traefik:
    external: true

services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ee:latest
    restart: unless-stopped
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/localtime:/etc/localtime:ro
      - /:/host:ro  # Host filesystem access (equivalent to -v /:/host)
    networks:
      - portainer_network
      - traefik
    ports:
      - "8000:8000"   # Portainer Agent communication
      - "9000:9000"   # HTTP port for Traefik backend (internal network only via UFW)
      - "127.0.0.1:9443:9443"   # HTTPS port for direct access fallback
    environment:
      - TZ=${TIMEZONE:-America/New_York}
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      # Traefik labels
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.portainer.rule=Host(`portainer.martin-ohana.com`)"
      - "traefik.http.routers.portainer.entrypoints=websecure"
      - "traefik.http.routers.portainer.tls=true"
      - "traefik.http.routers.portainer.tls.certresolver=cloudflare"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"

  portainer-agent:
    container_name: portainer-agent
    image: portainer/agent:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/lib/docker/volumes:/var/lib/docker/volumes:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - portainer_network
    ports:
      - "9001:9001"   # Agent communication port
    environment:
      - TZ=${TIMEZONE:-America/New_York}
      - AGENT_CLUSTER_ADDR=portainer-agent
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

volumes:
  portainer_data:
    driver: local
