services:
  influxdb:
    image: influxdb:2.7-alpine
    container_name: influxdb
    restart: unless-stopped
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=homelab
      - DOCKER_INFLUXDB_INIT_BUCKET=monitoring
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUXDB_TOKEN}
    volumes:
      - influxdb_data:/var/lib/influxdb2
      - influxdb_config:/etc/influxdb2
    networks:
      - monitoring
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.influxdb.rule=Host(`influxdb.martin-ohana.com`)"
      - "traefik.http.routers.influxdb.tls=true"
      - "traefik.http.routers.influxdb.tls.certresolver=cloudflare"
      - "traefik.http.services.influxdb.loadbalancer.server.port=8086"
    ports:
      - "8086:8086"

  grafana:
    image: grafana/grafana:10.4.2
    container_name: grafana
    restart: unless-stopped
    user: "472:472"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SERVER_DOMAIN=grafana.martin-ohana.com
      - GF_SERVER_ROOT_URL=https://grafana.martin-ohana.com
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource,grafana-worldmap-panel
      - GF_FEATURE_TOGGLES_ENABLE=publicDashboards
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - monitoring
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.rule=Host(`grafana.martin-ohana.com`)"
      - "traefik.http.routers.grafana.tls=true"
      - "traefik.http.routers.grafana.tls.certresolver=cloudflare"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"

  telegraf:
    build:
      context: ../../configs/telegraf
      dockerfile: Dockerfile
    container_name: telegraf
    hostname: ha-server2
    restart: unless-stopped
    user: telegraf:119
    environment:
      - INFLUXDB_TOKEN=${INFLUXDB_TOKEN}
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_ORG=homelab
      - INFLUXDB_BUCKET=monitoring
      - HA_TOKEN=${HA_TOKEN}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PIHOLE_PASSWORD=${PIHOLE_PASSWORD}
    volumes:
      - /home/cliffm/home-automation/configs/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc:/host/etc:ro
      - /var/run/utmp:/var/run/utmp:ro
      - /home/cliffm/.ssh:/root/.ssh:ro
    networks:
      - monitoring
      - traefik
      - home-automation
    privileged: true
    depends_on:
      - influxdb

  node_exporter:
    image: prom/node-exporter:v1.7.0
    container_name: node_exporter
    restart: unless-stopped
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    networks:
      - monitoring
    ports:
      - "9100:9100"

networks:
  monitoring:
    driver: bridge
    name: monitoring
  traefik:
    external: true
    name: traefik
  home_automation:
    external: true
    name: home_automation

volumes:
  influxdb_data:
    name: influxdb_data
  influxdb_config:
    name: influxdb_config
  grafana_data:
    name: grafana_data

